Fortran-FOSS-Programmers/ford

- ford/__init__.py
- ford/fortran_project.py
- ford/reader.py
- ford/sourceform.py
predocmark defaults to '' which does not recognize any anticipated
documentation. Setting it to '>' allows, for instance, documenting the
code as
!> Some documentation
!! for the varibale i
integer :: i
> Add an option "predocmark" for anticipated doc.

- ford/__init__.py
- ford/fortran_project.py
- ford/reader.py
- ford/sourceform.py
I 've implemented a patch, which enables a customizable preprocessor. If `preprocessor` is specified in the project file, the command line specified therein is used (extended with the name of the file to process and the eventual `-D` `-I` options), otherwise it falls back to the old `gfortran -E -cpp` command line.
It also fixes the problem with Python3, that stdout/stderr from `Popen.communicate()` is a byte stream by default, which one can't pass to `StringIO`.
> Implement customizable preprocessor.

- ford/templates/base.html
Using a protocol-relative address for the script as described in the [MathJax docu](http://docs.mathjax.org/en/latest/start.html#secure-access-to-the-cdn), would allow the LaTeX rendering to work for both protocols.
> Allow rendering of MathJax in HTTP aswell as HTTPS connections.

- ford/utils.py
It can be very puzzling for a user to find out, why Ford does not produce any output or error messages, when the current directory is deeper than ten levels (took me about an hour to realize...) Patch below would set the allowed depth higher and create a meaningful error message, if it is exceeded.
> Fix ford not to exit silently when encountering deep paths.

- ford/pagetree.py
This simple change allows you to specify the order by which the pages appear by changing the names of the file and directories. 
For example,  the following directory structure 
```
page_dir
├── index.md (README)
├── 01_changelog.md (ChangeLog)
├── 02_equations.md (Fluid Equations)
├── 03_examples
|   ├── index.md (Example Simulations)
|   ├── 02_shock.md (1D shock tube)
|   └── 01_collapse.md (Collapsing gas cloud)
└── 04_todo.md (ToDo)
```
will produce the following page heirarchy
```
README
├── ChangeLog
├── Fluid Equations
├── Example Simulations
|   ├── Collapsing gas cloud
|   └── 1D shock tube
└── ToDo
```
> Sort page files and directories alphabetically. Fixes #121

- ford/sourceform.py
In Fortran 2003 and 2008 USE statements are of the form:
USE [ [ , module-nature ] :: ] module-name ...
Modified USE_RE to recognize modules USEd using the syntax:
use :: module-name
> Regex for USE statements now recognizes "use :: module-name". Fixes #120

- ford/sourceform.py
Fixed the following bug when using Python 3:
````python
File "/anaconda/lib/python3.4/site-packages/ford/sourceform.py", line 832, in correlate
self.pub_procs.update([(name, proc) for name, proc in procs.iteritems() if name in self.public_list])
AttributeError: 'dict' object has no attribute 'iteritems'
````
My editor also did a lot of whitespace cleanup...I can revert that if you want.
> fixed python3 bug.

- ford/templates/base.html
For large projects the rendering of pages gets really slow. I think this is caused by a big tipuesearch_content.js file (about 70 MB for our project) which is loaded at the html head. My suggestion is to move this to the bottom, so that the rendering can take place first.
> Reducing page rendering time

- ford/__init__.py
- ford/output.py
- ford/templates/base.html
The option mathjax_config can be used to select a javascript file with
additional MathJax settings. As described here:
https://docs.mathjax.org/en/latest/configuration.html#using-plain-javascript
it is possible to define a MathJax object which will then be used in the
initial configuration of MathJax. A typical usage could be defining
custom latex macros as described in
https://docs.mathjax.org/en/latest/tex.html#defining-tex-macros
Hence, given a file my-path/MathJax-my-latex-macros.js containing
window.MathJax = {
TeX: {
Macros: {
RR: "{\\bf R}",
bold: ["{\\bf #1}",1],
Abs: ['\\left\\lvert #2 \\right\\rvert_{\\text{#1}}', 2, ""]
}
}
}
one can set
mathjax_config: my-path/MathJax-my-latex-macros.js
and use the latex macros \RR, \bold and \Abs anywhere in the ford
documentation.
> Added an option mathjax_config for custom setting.

- ford/sourceform.py
Apparently there were 3 statements of replacing content. However,
only the last statement was in use because of upper level
dependency. (item.name vs. name).
This fixes the naming scheme.
Signed-off-by: Nick Papior <nickpapior@gmail.com>
> bug: fixed replacements in name conversion

- ford/fortran_project.py
This patch lets ford skip all the subdirectories of the directories
listed in exclude_dir. Right now, only directories matching exactly
those listed in exclude_dir list are skipped.
The first commit is the real one, the second simply changes the
indentation. The two have been separated to simplify the diffs.
> Skip subdirectories of directories listed in exclude_dir

- ford/__init__.py
- ford/fortran_project.py
- ford/output.py
- ford/sourceform.py
- ford/templates/base.html
Quite a bit of segments around the code was using
list merges to simplify loops. However, this comes at the
price of duplicating lists while merging two lists.
This commit introduces itterators for compressing lists
while still retaining the order.
Secondly, the dbg option does not work (ford --debug)
does not accept debug. It is now True by default.
Signed-off-by: Nick Papior <nickpapior@gmail.com>
> enh: reduced memory consumption and speeded up process

- ford/reader.py
- ford/sourceform.py
We want to avoid asking the preprocessor to define a macro consisting of
an empty string: 'cpp -D file' defines the macro "file" and processes
standard input, for example.
We also consider the problem of arithmetic GOTOs (#207).
> Filter empty preprocessor flags; don't treat arithmetic gotos as function references

- ford/graphs.py
In #231 an issue was raised with empty lists for the FortranGraph. I think, the best approach to this setting is to assume warnings, if any of the root objects has warnings activated, instead of trying to get the value from the first entry in the list.
This change implements this logic and thereby should avoid issues with empty lists.
> Activate graph warnings if any object in the root list has warn true (#231)

- ford/css/local.css
- ford/graphs.py
4cf63d88cab97397b4b230614c6b236c97bc2a0d disabled the alternative rendering of graphs where the first hop exceeded the graph_maxnodes setting as tables. With this change those tables are generated again, and their look is changed to better resemble the corresponding graphviz visualization after the updates to the graphlayout.
> Re-enable graphs as table and adapt them to changed graph layout.

- ford/output.py
Fixed a bug when a user provides a JS configuration file for MathJax. Previously FORD would crash when it tried to copy the JS file to a directory which doesn't exist. It now creates that directory first.
> Fixed copying MathJax config file

- README.md
- README.rst
This PR fixes the links to Doxygen and the project wiki (both are now unreachable) in the README files, and uses `https` links rather than `http` when possible.
Additionally it fixes a most-likely typo "hiearchical" -> "hierarchical".
> Fixing links in the README files

- ford/sourceform.py
This may be something that is worth using more widely to avoid potential duplication.
> Fix #273: Ensuring `set` is used for module uses data

- ford/css/local.css
This is a cleaner fix than the previous implementation that works on all elements. The existing fix breaks when the anchor is on a table row and ends up adding an unwanted horizontal offset.
See here for demo: https://jsfiddle.net/18evn5pk/
Uncomment the `:target:before` CSS to see the difference
Solution from: https://stackoverflow.com/a/56467997/2043465
`scroll-padding-top` has pretty widespread support: https://caniuse.com/#search=scroll-padding-top
> Fix anchors being hid by navbar for all elements

- ford/reader.py
> Fix: include files were only processed if the word "include" was lowercase

- ford/sourceform.py
This PR fixes the inability for submodule procedures to have `CONTAINS` statements, as reported in #245. By instance:
```fortran
module foo_module
interface
module subroutine foo()
end subroutine
end interface
end module
submodule(foo_module) foo_submodule
contains
module procedure foo
contains
subroutine bar()
end subroutine
end procedure
end submodule
```
> Allow submodule procedures to have CONTAINS statements

- ford/reader.py
The previous fix for this does not account for `continued=True`. The same behaviour should apply in this case.
The failure I saw was the next block checks if `line[-1] == '&'` but this line can be empty and hence indexing it at `-1` causes an exception.
> Prevent IndexError on single ampersands

- ford/__init__.py
- ford/__main__.py
```
👍 python -m ford
usage: __main__.py [-h] [-d SRC_DIR] [-p PAGE_DIR] [-o OUTPUT_DIR] [-s CSS] [-r REVISION] [--exclude EXCLUDE]
[--exclude_dir EXCLUDE_DIR] [-e EXTENSIONS] [-m MACRO] [-w] [--no-search] [-q] [-V] [--debug]
[-I INCLUDE]
project_file
__main__.py: error: the following arguments are required: project_file
🙅 ./ford.py 
usage: ford.py [-h] [-d SRC_DIR] [-p PAGE_DIR] [-o OUTPUT_DIR] [-s CSS] [-r REVISION] [--exclude EXCLUDE]
[--exclude_dir EXCLUDE_DIR] [-e EXTENSIONS] [-m MACRO] [-w] [--no-search] [-q] [-V] [--debug]
[-I INCLUDE]
project_file
ford.py: error: the following arguments are required: project_file
🙅
```
We might need to specify the executable name in https://github.com/Fortran-FOSS-Programmers/ford/blob/master/ford/__init__.py#L100
> Add support for python -m ford

- ford/sourceform.py
This prevents warnings like `DeprecationWarning: invalid escape sequence \s` from regexes. As regexes often contain escape sequences, best practice is to just make them all raw strings
> Use rawstring literals for regexes

- ford/__init__.py
- ford/fortran_project.py
Closes #343
The OpenACC still points to a PDF which is a bit of a shame, but I
couldn't see an HTML version on their website.
The Fortran wiki is probably still the best place for the intrinsic
modules. fortran-lang.org looks shinier, but it doesn't seem to have
all the info the wiki does.
Update OpenMP link to the official spec for 5.1
MPI links left for the time being: MPI 4.0 is out, but official spec
is still PDF-only at the moment. We should update this if an HTML
version is released
> Fix and update URLs for intrinsic modules.

- .github/workflows/test.yml
- .gitignore
- ford/__init__.py
- pyproject.toml
- setup.cfg
- setup.py
Note: after this, editable installs (`pip install -e .`) will not have
their version number updated automatically
> Convert setup.py to setup.cfg/pyproject.toml

- ford/templates/index.html
Previously setting `project_gitlab` in the configuration file would not lead to a find us on button appearing.
We may also wish to change line 13 to say "Gitlab" rather than "The web" as well.
> Make sure "Find us on" present if `project_gitlab` set

- ford/fortran_project.py
- test/test_md_inputs.py
The old check just crashed as python does not return -1, but instead throws an exception.
> Fixed invalid check for : character in extra_mods.

- ford/fortran_project.py
- test/test_md_inputs.py
This an additional issue that is probably unexpected behavior that I spotted while doing the previous fix. fortran_project defines a module variable INTRINSIC_MODS which has just the built-in fortran intrinsic mods. Then near the bit of code that I fixed in correlate (~line 193), it does
`non_local_mods = INTRINSIC_MODS`
If extra_mods are supplied, it adds them to non_local_mods which actually adds them to the module variable INTRINSIC_MODS too because of python name binding. This isn't a problem if this is run on just a single project but it is probably a bug.
> Fixed module variable INTRINSIC_MODS being changed implicitly. 

- ford/__init__.py
- test/conftest.py
- test/test_md_inputs.py
- test/test_projects/test_external_project.py
- test/test_utils.py
- test_data/external_project/external_project/doc.md
- test_data/external_project/top_level_project/doc.md
Aliases previously only worked in the main page and the "page" documentation, not in the source docstrings
A partial fix for #361
> Enable aliases in docstrings

- ford/__init__.py
- ford/fixed2free2.py
- ford/output.py
- ford/sourceform.py
- ford/tipue_search.py
This PR is (mainly) narrowly focused on the edge case of ford having to write out a file such as `operator (*).html`, which python will complain about. 
It also replaces explicit file open and closes with context managers, aka "with statements", that ensure files get closed. These changes should be inoffensive and `pytest` was ran before and after the commits with the same failing test, so I hope I can sneak these changes in. 
---
For main thrust of this PR, consider this Fortran source code from an [Emory class on overloading operators](http://www.mathcs.emory.edu/~cheung/Courses/561/Syllabus/6-Fortran/operators.html) that defines the `*` operator between a matrix `A` and a vector `v`: 
```fortran
! ========================================================
! How to define your own …
```
> add asterisks to list of mangled symbols

- requirements.txt
Looks like ford runtime needs `importlib-metadata` otherwise it would report the following runtime error
```
==> /usr/local/Cellar/ford/6.1.6/bin/ford /private/tmp/ford-test-20220106-65625-7mgpnh/test-project.md
Traceback (most recent call last):
File "/usr/local/Cellar/ford/6.1.6/bin/ford", line 5, in <module>
from ford import run
File "/usr/local/Cellar/ford/6.1.6/libexec/lib/python3.9/site-packages/ford/__init__.py", line 30, in <module>
import markdown
File "/usr/local/Cellar/ford/6.1.6/libexec/lib/python3.9/site-packages/markdown/__init__.py", line 29, in <module>
from .core import Markdown, markdown, markdownFromFile  # noqa: E402
File "/usr/local/Cellar/ford/6.1.6/libexec/lib/python3.9/site-packages/markdown/core.py", line 26, in <module>
from . import util
File …
```
> deps: need `importlib-metadata`

- ford/sourceform.py
- test/test_sourceform.py
Generally only encountered in fixed form source, fixes a bug for declarations like:
```fortran
real x
dimension x(:)
allocatable x
```
> Fix multiline attributes

- ford/utils.py
- test_data/external_project/external_project/src/external.f90
There is an issue with extended types when creating the serialization of objects for the json database. The extends property holds a `FortranType`, which json does not know how to serialize. Hence, we need to do an obj2dict for this attribute.
This change also expands the `external_project` in the `test_data` to include an extended type.
> External projects: deal with extended types

- ford/sourceform.py
- ford/utils.py
- test/test_projects/test_external_project.py
- test_data/external_project/top_level_project/doc.md
- test_data/external_project/top_level_project/src/top_level.f90
Fixes #395 by mocking out `urlopen` to return some faked data so that we don't rely on an external resource for the tests.
Also some clean up of the external project code itself
> Fix external project test

- ford/sourceform.py
- test/test_project.py
- test/test_sourceform.py
Fixes #388 
The issue was type declarations like
```fortran
type, public :: foo
private
integer :: bar
end type foo
```
the `private` statement, which is only meant to apply to the type's members, was clobbering the type's permission
> Fix `type` permission attributes

- ford/__init__.py
- test/test_initialisation.py
Fixes #389, #398
`gfortran -E` requires a special flag to read from `stdin`, so instead
pass `/dev/null` as a filename. This _should_ be more robust -- at
least, this is how we call the preprocessor elsewhere.
This might fail in other ways for other preprocessors. For instance,
`gfortran -E` emits a warning instead of a preprocessed stream when
passed `/dev/null` like this. It might be necessary to pass an empty
file instead. We also still don't check that flags/macros are passed correctly.
Also now immediately aborts with a helpful error message if the preprocessor check fails
> Fix for preprocessors that can't read from stdin

- example/example-project-file.md
- ford/__init__.py
- ford/fortran_project.py
- test/test_project.py
Fixes #407
`exclude` excludes files based solely on name and not path. 336075c changed this to exclude based on path instead
> Fix change to `exclude` behaviour

- ford/output.py
Only create the directory MathJax-config when it doesn't exist yet. Avoids a crash with FileExistsError, which I don't see why it should be fatal.
> Do not fail on existing MathJax-config directory

- ford/graphs.py
- ford/utils.py
- test_data/external_project/top_level_project/doc.md
In our project using an external subproject some links went missing, causing aborts of FORD, because some objects were unexpectedly `None`. The problem seems to be that `dict2obj` did not actually return the generated object sometimes. This led to the public lists of external modules containing keys with `None` values.
Returning the object in the recursive function seems to resolve this issue for me.
> External projects: Actually return the generated object in dict2obj

- ford/reader.py
- test/conftest.py
- test/test_initialisation.py
- test/test_reader.py
Fixes #423
Previously, if preprocessing emitted anything to stderr, we would fall
back to using the unpreprocessed file. Now we only do so if
preprocessing errors. Warnings are still reported
> Only fall back to unpreprocessed file if preprocessing fails

- ford/graphs.py
- ford/sourceform.py
- ford/utils.py
- test/test_projects/test_external_project.py
- test_data/external_project/external_project/src/external.f90
- test_data/external_project/top_level_project/doc.md
- test_data/external_project/top_level_project/src/top_level.f90
There is another issue with external projects, when we try to extend a type that is defined in an external project, we fail for type bound procedures, as they do not get exported, and similarly also for public variables in that type. For variables I don't want to include the documentation in the json serialization. Instead I insert a text with a link to the type we inherit the variable from. This doesn't seem to be proper though, yet. Maybe it needs to go through Markdown processing first? The make_links works however. (The example in the testsuite is updated accordingly to cover this case)
> External: Fix extending external types with

- README.md
- README.rst
I added FORD as a spack package and it was recently merged, so I added information and a version badge for installing FORD via spack package manager.
> Update README with spack installation and badge

- ford/graphmanager.py
- ford/graphs.py
Fixes #258
(and also #383 #411 )
Two part fix:
1. use `tqdm.contrib.concurrent.process_map` instead of
`multiprocessing.Pool.map`. This crashes instead of hanging, which
lets us see that we have a problem with...
2. `graphs.BaseNode.__hash__` uses `self.ident`, but this causes
issues when unpickling, seemingly because `pickle` uses `hash` but
also unpickles attributes in an unpredictable order
Added bonus that `tqdm.process_map` prints a progress bar as well
> Fix hang when creating graphs during writing documentation

- ford/fortran_project.py
- ford/graphs.py
- ford/output.py
- ford/sourceform.py
- test/test_project.py
- test/test_projects/test_external_project.py
- test/test_sourceform.py
- test_data/external_project/external_project/src/external.f90
- test_data/external_project/top_level_project/src/top_level.f90
Bugs fixed:
- linking to external modules used by procedures didn't work
- submodule statement matching included extraneous `::`
- invalid `extra_mods` in settings would only print warning, now hard error
Lots of code duplication removed, and a bunch of tests added
> Tidy `fortran_project.correlate` and fix some minor bugs

- ford/__init__.py
When I built the documentations of my project, I found garbled texts which are non-ascii characters in the produced index.html page. Then I modified the encoding of opening the project file in FORD, and got the correct texts.
I guess this happens because the default encoding of my OS is gbk, and FORD uses this setting since its encoding is not specified manually.
I think it is OK to force UTF-8 encoding for project file and this change will help to produce consistent output pages.
> read project file with utf8 encoding

- docs/user_guide/writing_documentation.rst
rst renderer displays backslashes literally, better don't escape them.
> Docs: rst fixes for LaTeX syntax

- ford/__init__.py
- test/test_initialisation.py
Fixes #458 
Minor breaking change: `--src_dir` consumes multiple arguments, so the project file must not immediately follow it:
```
$ ford --src_dir ./source docs.md # Error
$ ford docs.md --src_dir ./source # Ok
$ ford --src_dir ./source -- docs.md # Ok
```
Having looked at every project using FORD that I can see, this will not affect any of them (at least in their automated doc builds)
> Fix `src_dir` command line option

- setup.cfg
On install Ford-6.1.17 gentoo user repository (Gentoo GURU) package that built from PyPi source tarball the following warnings appears:
```
* QA Notice: setuptools warnings detected: *
*   Installing 'ford.css' as data is deprecated, please list it in `packages`.
*   Installing 'ford.fonts' as data is deprecated, please list it in `packages`.
*   Installing 'ford.js' as data is deprecated, please list it in `packages`.
*   Installing 'ford.templates' as data is deprecated, please list it in `packages`.
*   Installing 'ford.tipuesearch' as data is deprecated, please list it in `packages`.
*   Installing 'ford.tipuesearch.img' as data is deprecated, please list it in `packages`.
*   The license_file parameter is deprecated, use license_files instead.
```
The proposed patch should fix it and …
> Fix setuptools deprecation warnings

- example/src/ford_interfaces.f90
- ford/fixed2free2.py
- ford/pagetree.py
- ford/reader.py
- ford/sourceform.py
- ford/templates/genint_page.html
- ford/templates/macros.html
- ford/templates/mod_page.html
- ford/tipue_search.py
- test/test_example.py
- test/test_sourceform.py
Procedure pointers in `interface` blocks are now handled correctly and rendered as variables.
Fixes #477 
@mcocdawc If you're able, would you mind checking this branch for your use case?
> Handle procedure pointers and dummy procedures in interface blocks

- README.md
I use this badge on my Python projects. It's clickable to drill down what Python versions users have, etc.
> doc: add total PyPI download badge

- ford/templates/index.html
- Suppress frontpage section of files/modules/etc if max_frontpage_items=0 (headers were still displayed)
- Fix for not displaying the link to "All files/All modules/etc." below the `max_frontpage_items` items in each category
I haven't run the "Corpus regressions" workflow test on my branch ...
> Fix for max_frontpage_items

- docs/user_guide/project_file_options.rst
The link to https://pythonhosted.org/Markdown/extensions/meta_data.html does not exist. I'm pretty certain this is the right link: https://python-markdown.github.io/extensions/meta_data/
> Fixed broken link to Meta-Data reference

- docs/user_guide/project_file_options.rst
- ford/__init__.py
- ford/graphs.py
- ford/output.py
- test/test_graphs.py
add an option to show the parent module of procedures in their graphs.
this adds the functionality mentioned in #364
> Add `show_proc_parent` option for graphs

- ford/graphs.py
- ford/sourceform.py
- ford/templates/proc_page.html
- test/test_graphs.py
this commit tackles the following todo stated in the wiki:
"Add the ability to identify type-bound procedure calls and use these when constructing call-trees"
Type bound function calls will now show up in the call graph as follows:
typename%procname
Additionally, on the doc page for any procedure that is bound to a type, an additional header is added for the type that is bound, and links to the type.
> add typebound procedures to call graph, and show the bound type on procedures' page

- ford/sourceform.py
- test/test_sourceform.py
Fixes #505 
Also minor refactor of associated bound procedure bits
> Make double-colon in bound procedure declaration optional

- ford/graphs.py
- ford/utils.py
- test/test_graphs.py
procedures that are internal to a procedure will now show their calls in call graphs.
> fix internal procedure's calls not showing up in call graphs

- ford/graphs.py
- ford/sourceform.py
- ford/utils.py
- test/test_graphs.py
- test/test_sourceform.py
- test/test_utils.py
Fixes some cases where the parsing of call chain fails.
Specifically if there is white-space tailing the last % in the chain,
and if the call is made inside of square brackets.
> Fix call chain parsing for some edge cases

- ford/output.py
- ford/templates/absint_list.html
- ford/templates/block_list.html
- ford/templates/file_list.html
- ford/templates/macros.html
- ford/templates/proc_list.html
- ford/templates/prog_list.html
If we've not managed to catch the error during parsing, ford will often fail when trying to render the output page with a cryptic:
RuntimeError: 'str object' has no attribute 'meta'
This tries to be a bit more helpful and guide the user to the likely source of the error (which might still be due to a bug in ford)
> Try to give a more helpful error message when parsing has failed

- ford/sourceform.py
- ford/utils.py
- test/test_sourceform.py
- test/test_utils.py
@ZedThree , the refactor for the call chains parsing looks good, however, I've found a few issues with it that somehow made it past the tests. I've updated the tests to be more rigorous now, and should catch these issues now.
One issue was that the 'parent' group wasn't getting properly picked up when there were () in the call chain (for example when indexing into an array). Unfortunately I don't think this can't be done with regex alone because it requires bracket matching.
Another issue along the same vain was with the 'arguments' group for a subcall also not always being correct because of bracket matching.
To fix these issues, the contents of the parentheses are first striped prior to applying the regex. Then each layer of parentheses are stripped checked for matches. Additionally, …
> Fix call chains

- ford/sourceform.py
- test/test_project.py
- test/test_sourceform.py
fixes errors with module procedures when the display setting has 'private'
fixes errors when chain calls are made inside of a module procedure
removes unnecessary code in _find_call_context function
> fix issues in PR#528

- ford/fortran_project.py
- ford/sourceform.py
- test/test_project.py
- test/test_sourceform.py
There were a few cases where some labels (e.g. vars, proc names) are missing from contexts that they should be present in.
Here are the cases that this PR fixes:
in submodules, the parent module's private vars
in internal procedures, the parent procedure's args and return values
in interfaces, imported items via USE
in generic interfaces implementation, the attributes of the base interface
> Fix missing labels on codeunits

- ford/sourceform.py
- test/test_sourceform.py
refactors the call chain correlation to make it much simpler, and also adds some functionality to allow it to parse call chains that may have been modified by an association (association modified call chains might have a function call in the middle of the call chain)
recognizes associations and applies them to call chains. Additionally, the rhs of associations are called when the association is made, and these are now also added as call chains.
> Make calls recognize associations

- docs/user_guide/documentation_meta_data.rst
- docs/user_guide/project_file_options.rst
- docs/user_guide/running_ford.rst
- docs/user_guide/writing_documentation.rst
- Clarify that metadata in docstrings is always parsed, even if we don't use that key
- Fix some typos, links, and formatting
Fixes #530
> Fix some issues in docs

- test/test_example.py
- test/test_initialisation.py
- test/test_md_inputs.py
- One example test requires graphviz, so that should be conditionally skipped
- Some tests were checking path normalisation explicitly in POSIX format, so result in different plain text on Windows
- One test runs `true /dev/null` as a trial preprocessor, but this will fail on Windows. I'm not sure of a better solution myself, so just skip this on Windows
I'm not sure that the path normalisation tests are doing the correct thing -- we probably actually want to always use URL formatting of paths (see #515 for some discussion)
> Fix some tests for Windows

- ford/graphs.py
- ford/sourceform.py
- test/test_graphs.py
Fixes #538
Plus some other minor tidy-ups:
- fix "help" legend when pages have multiple graphs
- add type-bound procedures to graph legends
@JosephWood2001 I've changed the behaviour for type-bound procedures in call graphs slightly: they now count as "simple bindings" only if the single binding is visible. I wonder if this needs to be further refined. Maybe we should always add bound procedures anyway, even if they add a bit of clutter for simple bindings?
> Include type-bound procedures in call graphs if binding not visible 

- ford/__init__.py
- ford/_markdown.py
- ford/fortran_project.py
- ford/graphs.py
- ford/output.py
- ford/pagetree.py
- ford/settings.py
- ford/sourceform.py
- ford/templates/macros.html
- ford/templates/mod_list.html
- ford/templates/types_list.html
- ford/tipue_search.py
- ford/utils.py
- test/test_graphs.py
- test/test_initialisation.py
- test/test_project.py
- test/test_settings.py
- test/test_sourceform.py
- test/test_utils.py
Metadata set in an entity's docstring is now read as soon as possible and separately to the markdown conversion. This allows us to wait till after the correlate step to do the markdown conversion, which will be important for replacing `sub_links` with a markdown extension.
This PR also converts the entity metadata to a dataclass, which gives us better type checking and auto-completion, etc, for the metadata.
> Delay applying markdown conversion till after correlate step

- ford/__init__.py
- ford/_markdown.py
- ford/external_project.py
- ford/output.py
- ford/settings.py
- ford/sourceform.py
- ford/utils.py
- test/conftest.py
- test/test_example.py
- test/test_initialisation.py
- test/test_markdown.py
- test/test_md_inputs.py
- test/test_projects/test_external_project.py
- test/test_settings.py
- test/test_utils.py
This simplifies the markdown conversion a little by moving the alias substitution inside the `Markdown.convert` call.
Also move creation of the markdown object to as late as possible so that we can set the aliases from the settings object.
One downside to this approach is that it's no longer possible to detect duplicate aliases.
> Convert `sub_macros` to a markdown extension

- docs/user_guide/project_file_options.rst
- example/example-project-file.md
- ford/fortran_project.py
- ford/settings.py
- test/test_project.py
- Allow glob patterns like `**/test_*.f90`
- Automatically exclude `output_dir`
- Fix `--exclude_dir` set on command line not overriding `src_dir`
Fixes #259 
Fixes #349
> Improve `exclude` and `exclude_dir` options

- ford/__init__.py
- test/test_initialisation.py
Options should be specified as semicolon-separated TOML, for example:
ford --config="quiet = true; display = ['public']; alias = {a = 'b', c = 'd'}"
Fixes #481
> Add option to specify any project setting on the command line

- example/src/ford_test_module.fpp
- ford/sourceform.py
Unnamed interface blocks don't get their own separate page, but checking `.get_dir()` would return a directory name when it should be `None`.
> Fix for docstrings on unnamed interface blocks

- docs/user_guide/project_file_options.rst
- docs/user_guide/writing_documentation.rst
- ford/settings.py
- pyproject.toml
- test/test_reader.py
As this is a python package, we can install it by default, and so don't need to rely on `cpp` being installed on the host system
Fixes #567 
@bkmgit I tried your podman file locally with this change and it seems to work, but maybe you want to double check it too?
> Switch default preprocessor to `pcpp`

- ford/css/pygments.css
- ford/fortran_project.py
- ford/sourceform.py
- ford/templates/base.html
- ford/templates/info_page.html
Fixes #575 
@zoziha Please could you check to see if this fixes your issues?
Fixes:
- code blocks not wrapping
- code highlighting not working
- "Source File" navbar link not working for single file projects
- duplicated source files on case insensitive filesystems
> Fix some issues with code blocks and listing of source files

- ford/__init__.py
- ford/fortran_project.py
- ford/sourceform.py
- ford/utils.py
Fixes #577 
Stop a couple of crashes when some expected entities aren't found, and give some useful warnings
> Better errors for missing objects

- ford/sourceform.py
- test/test_projects/test_external_project.py
- test/test_sourceform.py
- test_data/external_project/top_level_project/src/top_level.f90
> Fix call chain following for external types

- ford/sourceform.py
- test/test_project.py
This seems to happen with deferred bound procedures
Fixes #591
> Handle entities that might not have be correlated in resolving links

- ford/__init__.py
- ford/settings.py
- test/test_initialisation.py
The command line arguments also have to conform with the `ProjectSettings` data types. With these changes they are also passed through the converter that is also used for the MD meta data. I am not quite sure if this is the proper way to go about it, but it resolves #601 for me.
> Ensure proper data types for command line arguments to fix #601

- ford/sourceform.py
Was previously using HTML named character reference `&nbsp;` which would be rendered literally when escaped. Using the unicode directly bypasses the jinja escaping
Fixes #605
Although a little confusing, as I cannot find when unicode whitespace is getting replaced with plain spaces.
> Replace multiple consecutive spaces with unicode non-breaking spaces

- docs/user_guide/writing_documentation.rst
- ford/_markdown.py
- test/test_markdown.py
Fixes #604
Turns out this was a bit more complicated than expected as tables are "block processors" and I had implemented aliases as "inline processors", which always run after block processors. So this required rewriting the processor as a "preprocessor" which always run before block processors.
> Fix clash between table and alias syntax

- docs/user_guide/project_file_options.rst
Hi,
This PR fixes a typo in `docs/user_guide/project_file_options.rst`.
> Fix typo in docs

- ford/sourceform.py
- test/test_sourceform.py
> Fix type definition in `block` breaking parent scope

- ford/templates/base.html
- ford/templates/block_page.html
- ford/templates/index.html
- ford/templates/nongenint_page.html
- ford/templates/proc_page.html
- ford/templates/prog_page.html
- ford/templates/type_page.html
- Fix empty jumbtron and odd footer if no author or summary provided (see #633)
- Add some macros to simplify buttons
- Remove `|length > 0` from jinja templates
> Small cleanup of frontpage template

- ford/sourceform.py
- test/test_project.py
The `hide_undoc` flag didn't work correctly. When running FORD on a project with the `hide_undoc` flag set to `true`, FORD crashes with the following traceback:
```
Traceback (most recent call last):
File "/home/thundermoose/ExternalGits/ford/ford.py", line 7, in <module>
run()
File "/home/thundermoose/ExternalGits/ford/ford/__init__.py", line 489, in run
main(proj_data, proj_docs)
File "/home/thundermoose/ExternalGits/ford/ford/__init__.py", line 420, in main
project.correlate()
File "/home/thundermoose/ExternalGits/ford/ford/fortran_project.py", line 343, in correlate
container.prune()
File "/home/thundermoose/ExternalGits/ford/ford/sourceform.py", line 1415, in prune
self.functions = self.filter_display(self.functions)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File …
```
> Fix bug with `hide_undoc = True`

- ford/templates/namelist_page.html
The pull request replaces `%ndash;` with `&ndash;` in the title of the template.
> Fix `namelist` page title

- test/test_corpus.py
- Add include paths
- Turn off FFTs and eigenvalue solver (alt: install PETSc and FFTW into runner and pass flags)
- Init git submodules
> Fix corpus test for recent GS2 release

- ford/sourceform.py
- test/test_sourceform.py
This probably actually too loose, but seems to work ok
Related to #475
> Fix issue with no whitespace between type and `function`

- pyproject.toml
As per [the info in PyPi](https://pypi.org/project/setuptools-scm-git-archive/),
> This plugin is obsolete. `setuptools_scm >= 7.0.0` supports Git archives by itself.
Building and running `pytest` after removing `setuptools_scm_git_archive` returns no errors.
I added FORD to the [AUR](https://aur.archlinux.org/packages/ford) and added this change as a [patch](https://aur.archlinux.org/cgit/aur.git/tree/pyproject.toml.patch?h=ford) because `setuptools-scm-git-archive` is not available on Arch.
Thank you for your time.
> Remove setuptools_scm_git_archive from build requirements

- ford/settings.py
- test/test_settings.py
> Fix error detection when parsing `extra_filetype`

- ford/__init__.py
`datetime.now()` returns a naive timestamp in the local TZ. When formatting this timestamp, `%z` and `%Z` directives would therefore always be empty.
This commit calls `.astimezone()` to attach the system TZ to this timestamp. `%z` and `%Z` directives when formatting the timestamp are now respected.
> make creation_date timezone-aware

- ford/md_admonition.py
Drops the priority of the admonition to <= markdown_include to ensure included files get admonition's rendered correctly
> Update md_admonition.py to fix issue #665

- README.md
Tipue website no longer for Tipue search (which appears deprecated).
> Update README.md to remove incorrect Tipue Search link

- README.md
I note that the spack package config has not been updated for quite some time and offers no v7 builds. https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/py-ford/package.py
> Update README.md to fix spack badge link

- ford/sourceform.py
Tweaks SRC_CAPTURE_STR to avoid capturing the logical groups in this regex as we don't use them.  This gives a slight optimisation to the "Processing comments" stage.
There are likely a few other places in sourceform that similar adjustments could be made, but they are less likely to give a noticeable speed up as, at least for the project I'm testing with, the SRC_CAPTURE_STR regex search dominates the processing comments stage.
> Don't store sub-groups where not needed in regex and other processing optimisations

- ford/templates/base.html
Updates to the current newest bootstrap. May need user testing to check nothing has broken in the presentation.
> Update base.html to point to bootstrap 5.3.3

- ford/reader.py
When using `pcpp` we can avoid using subprocess to call the `pcpp` executable and simply construct a `CmdPreprocessor` object directly. This can save a little potential overhead of starting new processes.
> Experimental: Avoid subprocess in preprocessing

- docs/user_guide/writing_documentation.rst
- ford/_markdown.py
- test/test_markdown.py
Pull request for issue #678 
Add backslash as escape character for `alias`, such that `\|foo|` is not replaced, while `|foo|` is.
> Add backslash as escape for alias

- ford/_markdown.py
- ford/intrinsics.py
- ford/output.py
- ford/tipue_search.py
- test/test_markdown.py
> Fix warning about invalid escape sequence in docstring

- ford/external_project.py
- ford/graphs.py
- ford/settings.py
- ford/sourceform.py
- ford/templates/macros.html
- test/test_projects/test_676.py
- test_data/issue_676/base/doc.md
- test_data/issue_676/base/src/gc_method_h.f90
- test_data/issue_676/base/src/gc_pointers_h.f90
- test_data/issue_676/plugin/doc.md
- test_data/issue_676/plugin/src/gc_method_fks_h.f90
> Deal with external type bound procedures without local overwrite

- ford/settings.py
- test/test_settings.py
Closes #686
Example error message:
```
ValueError: Error parsing settings from 'example-project-file.md': Fixed-form extension 'f' also appears in free-form extension list (`extensions = ['f']`)
```
In the interests of getting something in, this just raises an
exception, rather than trying to be clever and automatically remove it
from the fixed-form list. Hopefully the error message is clear enough.
@banana-bred Thoughts?
> Raise error if fixed-form extension also appears in `extensions`

- ford/_markdown.py
- ford/sourceform.py
Closes #691
Example of new error message:
```
ValueError: Error when rendering docstring for type 'foo' in 'ford_test_program.f90':
Error when parsing link '[[foo(type):do_foo_stuff(subroutine)]]': 'type' cannot have child 'subroutine'
```
@runburg Thoughts?
> Make error message when failing to parse ford link a bit friendlier

- ford/_markdown.py
- test/test_projects/test_external_project.py
- test_data/external_project/top_level_project/src/top_level.f90
Fixes #696
We've been testing that Ford's automatic links all work correctly with external projects, and hadn't actually checked that users' links work.
> Fix `[[ford]]` links to external entities

- ford/settings.py
- ford/sourceform.py
Two separate issues found from investigating #696 
Closes #699
> Fix external type bound procedures

- docs/user_guide/project_file_options.rst
- ford/__init__.py
The [project file options](https://forddocs.readthedocs.io/en/stable/user_guide/project_file_options.html) allow selecting a project license. This change adds support for the GNU License Family, including:
- GNU General Public License (GPL)
- GNU Lesser General Public License (LGPL)
- GNU Affero General Public License (AGPL)
For more details, see the documentation:
https://forddocs.readthedocs.io/en/stable/user_guide/project_file_options.html#license
Let me know if any refinements are needed!
> Add GNU License Family

- ford/sourceform.py
- test/test_sourceform.py
When the `summary` key is used in documentation metadata, FORD generates garbled contents for the summary field of the documented program unit.
For example, with the documentation metadata below,
```
!> summary: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
!>          Fusce ultrices tortor et felis tempus vehicula.
!>          Nulla gravida, magna ut pharetra.
```
FORD generates the following HTML source code, which is obviously incorrect:
```
<p>L\no\nr\ne\nm</p>\n<p>i\np\ns\nu\nm</p>\n<p>d\no\nl\no\nr</p>\n<p>s\ni\nt</p>\n<p>a\nm\ne\nt\n,</p>\n<p>c\no\nn\ns\ne\nc\nt\ne\nt\nu\nr</p>\n<p>a\nd\ni\np\ni\ns\nc\ni\nn\ng</p>\n<p>e\nl\ni\nt\n.</p>\n<p>F\nu\ns\nc\ne</p>\n<p>u\nl\nt\nr\ni\nc\ne\ns</p>\n<p>t\no\nr\nt\no\nr</p>\n<p>e\nt</p>\n<p>f\ne\nl\ni\ns</p>\n<p>t\ne\nm\np\nu\ns</p>\ …
```
> Fix incorrect handling for the `summary` key in documentation metadata
