Fortran-FOSS-Programmers/ford

- ford/__init__.py
- ford/fortran_project.py
- ford/output.py
- ford/reader.py
- ford/sourceform.py
Should now work with either Python 2 or Python 3.  See Issue #19.
> Python 3 compatibility

- README.md
- README.rst
Added Homebrew install instructions to READMEs
> homebrew documentation patch

- README.md
- README.rst
> Zbeekman homebrew patch

- README.md
This is probably not the most opportune time to be opening this PR since it appears shields.io is having some issues, but I thought it might be worthwhile to add PyPi and Github release version badges to the README.md.
Let's wait until shields.io comes back online to merge these changes, though, so we can get an accurate preview.
> Add PyPi and release badges

- README.md
Comment out release badge since shields.io has been broken for quite a while now
Add manually coded license badge
> Fix problem with pypi badge

- ford/output.py
categroy --> category, not sure if this has any impact on anything.
> Fix minor typo in tipuesearch create_node call

- ford/sourceform.py
I think this could fix the case sensitivity of graphs raised in #193.
> Be case insensitive when searching for entities which are imported by a use statement.

- example-project-file.md
- src-example/ford_test_program.f90
Hi Chris,
I just thought I would add an example src directory to the git repo so that one can directly invoke `ford example-project-file.md` after installing ford and cloning this repo. What do you think?
> Better example

- ford/graphmanager.py
Turning meta['graph'] to all lower case when checking the setting.
> Addressing #219

- ford/reader.py
- I've found that it's extremely helpful to simply put the line value in each raised Exception, so that the user knows where to fix the code.
> Add source code line values to raised exceptions

- ford/sourceform.py
Thanks for making FORD! This is just a tiny fix.
> Fix invalid "Read more" for components of derived types

- ford/sourceform.py
> sourceform: Check for both function calls and sub calls on same line

- ford/sourceform.py
Thanks to @albgar for submitting this patch!
> Fix 267: Inc. all proc doc when missing read more

- ford/sourceform.py
this pull request enables the recognitionof the data type `double complex.` 
It is in response to #251 .
> recognizing data type: double complex (issue #251)

- ford/reader.py
If a header file is not found, that shouldn't be treated as an error,
header files are typically from different projects, and not adding
documentation for them is fine.
Resolves #312
> Warn on missing include files instead of error

- ford/sourceform.py
- test/test_sourceform.py
Fixes #296
@jacobwilliams Seeing as you wrote the fix and reproducer, I've set you as the author for this commit. If you'd prefer I didn't please let me know and I'll change it
> Fix for crash when character default value contains backslash

- .github/workflows/black.yml
- ford/__init__.py
- ford/fixed2free2.py
- ford/fortran_project.py
- ford/graphmanager.py
- ford/graphs.py
- ford/mdx_math.py
- ford/output.py
- ford/pagetree.py
- ford/reader.py
- ford/sourceform.py
- ford/tipue_search.py
- ford/utils.py
- setup.py
This is a big formatting change to the entire project -- any forks will now have big diffs unless they also apply [black](https://black.readthedocs.io/en/stable/).
Also adds a Github Action that automatically applies `black` to the repo so it formatting should now be entirely hands-off.
Closes #334
> Apply `black` formatting to project; add auto-black to CI

- ford/__init__.py
- ford/fixed2free2.py
- ford/fortran_project.py
- ford/graphmanager.py
- ford/graphs.py
- ford/output.py
- ford/pagetree.py
- ford/reader.py
- ford/sourceform.py
- ford/tipue_search.py
- ford/utils.py
> Fix flake8 warnings

- ford/__init__.py
- ford/pagetree.py
- ford/sourceform.py
- test/test_pagetree.py
- test/test_sourceform.py
- Fix #286 
- Fix #287 
- Fix #327
Plus more tests and a little bit of tidying up.
> Fix indentation in markdown blocks and footnotes appearing on multiple pages

- example/src/ford_test_program.f90
- ford/__init__.py
- ford/sourceform.py
- ford/utils.py
- test/test_project.py
- test/test_sourceform.py
- test/test_utils.py
> Fix showing source in generated docs

- example/example-project-file.md
- example/src/excluded_directory/this_file_will_not_be_included.f90
- example/src/excluded_file.f90
- example/src/ford_test_program.f90
- ford/__init__.py
- ford/fortran_project.py
- ford/sourceform.py
- ford/utils.py
- test/test_project.py
- test/test_sourceform.py
- test/test_utils.py
Fixes #391 
Includes #390 to reduce conflicts
> Fix `exclude_dirs`

- ford/sourceform.py
- test/test_project.py
Fixes #303
Plus refactoring and more tests
> Fix bad conversion to `str` in `sort: type-alpha`

- ford/sourceform.py
This causes issues with later looking up entities
> Fix filtering public entities not lowercasing name

- example/example-project-file.md
- ford/output.py
- ford/tipue_search.py
- Use `pathlib.Path`
- Reduce code duplication
> Minor refactoring of `output.py`

- ford/__init__.py
This PR adds an argument to the command parser to enable graph generation from the command. This way you don't have to open up the project file, change it, save, and rerun if you just want to toggle the graphs.
> Added `-g`/`--graph` argument to command parser.

- setup.cfg
> Pin dependencies; bump required `markdown-include` version

- example/example-project-file.md
- ford/fortran_project.py
- test/test_project.py
Fixes #436
Also add test for the module `use` tree correlation
> Fix quoted URLs in `extra_mods` input not being removed

- .github/workflows/test.yml
- example/src/ford_test_module.fpp
- ford/graphs.py
- setup.cfg
- test/test_example.py
> Fix bad attribute rename

- example/example-project-file.md
- example/src/ford_example_type.f90
- ford/sourceform.py
- ford/templates/macros.html
- test/test_example.py
- test/test_sourceform.py
> Fix type-bound procedure docs not showing full docstring

- .git-blame-ignore-revs
- docs/user_guide/command_line_options.rst
- ford/__init__.py
- test/test_initialisation.py
I didn't think this through: the CLI default values will override values in the project file, which is not what we want at all.
> Revert adding default values to CLI interface

- example/src/ford_test_module.fpp
- ford/sourceform.py
- ford/templates/macros.html
- ford/templates/mod_page.html
- test/test_example.py
- test/test_project.py
- test/test_sourceform.py
> Some fixes for module procedures

- docs/conf.py
- setup.cfg
> Fix command line option docs

- .github/workflows/test.yml
- .gitignore
- test/test_sourceform.py
> Fix tests for Python 3.11

- ford/__init__.py
- ford/fortran_project.py
- ford/graphs.py
- ford/sourceform.py
- test/test_graphs.py
- test/test_project.py
- test/test_sourceform.py
> Fix some regressions in graphs

- ford/sourceform.py
- test/test_sourceform.py
> Fix parsing character declarations when `len=` is not present

- ford/graphs.py
- test/test_graphs.py
> Try to be much more consistent about handling `str` in graphs

- ford/graphs.py
- test/test_graphs.py
> Fix displaying graphs as tables

- ford/sourceform.py
- ford/utils.py
- test/test_sourceform.py
Various small refactorings and tidy-ups
> Some minor refactoring

- docs/api/ford.external_project.rst
- docs/api/ford.rst
- docs/api/ford.settings.rst
- docs/api/ford.version.rst
- ford/__init__.py
- ford/_markdown.py
- ford/_typing.py
- ford/fortran_project.py
- ford/graphs.py
- ford/output.py
- ford/pagetree.py
- ford/reader.py
- ford/settings.py
- ford/sourceform.py
- test/test_example.py
- test/test_graphs.py
- test/test_initialisation.py
- test/test_project.py
- test/test_settings.py
- test/test_sourceform.py
Enables better name/type checking throughout code
> Convert settings to a dataclass

- ford/_markdown.py
- ford/sourceform.py
- ford/templates/macros.html
- test/test_graphs.py
- test/test_project.py
Closes #546
This has the potential to change how current links are resolved, if there is a more local name that a link could point to. These can be fixed by specify the entity class and/or parent
> Resolve Ford links in context of current entity

- ford/__init__.py
- ford/_markdown.py
- ford/console.py
- ford/fortran_project.py
- ford/graphs.py
- ford/output.py
- ford/pagetree.py
- ford/reader.py
- ford/settings.py
- ford/sourceform.py
- ford/utils.py
- pyproject.toml
- test/test_sourceform.py
All the phases now have progress bars, giving the user more feedback on progress.
Also:
- give some timing information on correlating and HTML output phases
- colour in warning messages
> More and fancier progress bars using `rich`

- example/pages/subdir/index.md
- example/pages/subdir/subsubpage.md
- ford/__init__.py
- ford/_markdown.py
- ford/css/local.css
- ford/pagetree.py
- ford/settings.py
- ford/templates/info_page.html
- ford/utils.py
- test/test_example.py
- test/test_markdown.py
- test/test_md_inputs.py
- test/test_pagetree.py
- test/test_settings.py
> Fix relative urls on nested pages from expanded aliases 

- example/src/ford_example_type.f90
- ford/sourceform.py
- ford/templates/base.html
- ford/templates/macros.html
- ford/templates/type_page.html
- test/test_example.py
- test/test_sourceform.py
- Extra comma in procedure declaration
- Displaying full docstring when bound procedure has own page
- Double counting of generic type bound procedures
Fixes #565
> Fix some display issues for type bound procedures

- example/example-project-file.md
- ford/fortran_project.py
> Fix links to intrinsic mods

- ford/md_admonition.py
- test/test_md_admonition.py
> Fix admonitions without a trailing newline

- test/test_corpus.py
One of the projects was recently renamed
> Fix corpus tests

- ford/graphs.py
- ford/templates/base.html
> Fix some graph issues

- ford/fortran_project.py
- ford/graphs.py
- ford/settings.py
- ford/sourceform.py
- ford/templates/macros.html
- ford/templates/type_page.html
- pyproject.toml
- test/conftest.py
- test/test_example.py
- test/test_graphs.py
- test/test_project.py
- test/test_projects/test_external_project.py
- test/test_sourceform.py
* Fix links to external modules in graphs
* Guard against total being zero in `lines_description`
* Warn on any unhandled attributes
* Fix rendering of html in LOC tooltip
* Parse array constructors in `associate` statements correctly
* Fix display of derived type attributes
* Fix large/incomplete graphs being wrongly rendered
> Various minor bug fixes

- ford/fortran_project.py
- ford/sourceform.py
- test/test_project.py
> Make link names case-insensitive

- ford/templates/base.html
> Fix a couple more instances of relative links in the navbar

- docs/api/ford._markdown.rst
- docs/api/ford.rst
- docs/developers_guide/index.rst
- docs/user_guide/writing_documentation.rst
- ford/_markdown.py
- ford/fortran_project.py
- test/test_project.py
Fixes #499 
Also updates some of the docs around linking and processing markdown
> Enable linking to submodules

- ford/output.py
Fixes #648
@econwang Are you able to test this branch on Windows and verify it fixes the problem for you?
> Don't try to fix relative links if they already start with "http"

- ford/templates/macros.html
> Fix extraneous `relurl` in type-bound procedure list
